// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvfwpbaqgbopaskleyff.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2ZndwYmFxZ2JvcGFza2xleWZmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODg3NzksImV4cCI6MjA2ODk2NDc3OX0.5YC6OwM6XqVycU1BfBLGczDPYL-kxmLMD-3iToxAU7M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});